baseURL = "https://fdio-poc.netlify.app/"
title = "The Fast Data Project (FD.io)"
author = "John DeNisco"
copyright = "Copyright © 2021, John DeNisco; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

theme = "hugo-casper3"

[taxonomies]
  category = "categories"

[params]
  logo = "/images/fdio-color.svg"
  subTitle = "An open-source project aimed at providing the world's fastest and most secure networking data plane through Vector Packet Processing (VPP)"
  mainSections = ["home", "pmc"]

[params.widgets]
    categories = true

[params.slider]
  enable = false
  manual = true # Setting manual to true renders the slide selection to only those where the post has a slider=true option enabled
  num_features = 10 # The slider picks up the banner images from the N most recent posts, where num_features is N.

[menu]
  [[menu.main]]
    identifier = "latest"
    name = "The Latest"
    url = "/latest"
    weight = 10

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = ""
    weight = 20

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = ""
    weight = 30

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = ""
    weight = 40

[privacy]
  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
